### Get All Cards - RUNNING THIS WILL CRASH VS CODE
https://db.ygoprodeck.com/api/v7/cardinfo.php

### Search All Cards With "Magician" in Name
https://db.ygoprodeck.com/api/v7/cardinfo.php?fname=Tyler&misc=yes

### Random Card
https://db.ygoprodeck.com/api/v7/randomcard.php?language=en

### All Card Sets
https://db.ygoprodeck.com/api/v7/cardsets.php

### Card Set Information
https://db.ygoprodeck.com/api/v7/cardsetsinfo.php?setcode=SDY-046

### All Card Archetypes
https://db.ygoprodeck.com/api/v7/archetypes.php

### Check Database Version
https://db.ygoprodeck.com/api/v7/checkDBVer.php